"""Regression test: the time-stepped displacement stays solenoidal.

The reduced Kelvin-Voigt equation ``rho u_tt = mu lap(u) + eta lap(u_t) + f_S``
is only a shear-wave model if ``div u = 0`` is preserved.  In a homogeneous
medium the componentwise Laplacian commutes with the discrete divergence in
the interior, so ``div u`` can only be generated by (a) a non-solenoidal
projected force or (b) the zero-Dirichlet box wall, which is not
solenoidal-preserving and is excited from the first step because the
Helmholtz-projected force is non-local.  Wall-generated divergence travels
inward at the shear speed, so a region ``L`` voxels from the wall is clean
until ``t = L / c_s``.

This test drives a homogeneous cube with a localized axial body force and
asserts that ``RMS(div u) / RMS(|curl u|)`` over the inner half-cube stays
below ``TOL`` until the wall signal arrives, and for the whole run when
``reproject_every`` is used.  The pre-July-2026 projection (which inverted the
compact Laplacian) gives a ratio of order 0.3 on this setup from step one.
"""

import math

import numpy as np
import pytest

from shearwave.solver import shear_fdtd

TOL = 1e-4  # observed: 1e-6 .. 2e-5 before wall arrival (float32), independent of damping


def _div_curl_ratio(u, d):
    """RMS(div u)/RMS(|curl u|) with 2h central differences over the inner half-cube."""
    j = [np.gradient(u[..., i].astype(np.float64), d, d, d, edge_order=1) for i in range(3)]
    div = j[0][0] + j[1][1] + j[2][2]
    cx = j[2][1] - j[1][2]
    cy = j[0][2] - j[2][0]
    cz = j[1][0] - j[0][1]
    curl = np.sqrt(cx * cx + cy * cy + cz * cz)
    n = u.shape[0]
    q = n // 4
    sl = (slice(q, n - q),) * 3
    return float(np.sqrt(np.mean(div[sl] ** 2)) / np.sqrt(np.mean(curl[sl] ** 2)))


def _setup(n=32, d=1.0e-3, mu=4580.0, rho=1000.0):
    """Gaussian axial push at the centre of an n^3 cube; returns force and time step."""
    ax = (np.arange(n) - (n - 1) / 2) * d
    x, y, z = np.meshgrid(ax, ax, ax, indexing="ij")
    sigma = 2.5 * d
    bx = (300.0 * np.exp(-(x**2 + y**2 + z**2) / (2 * sigma**2))).astype(np.float32)
    cs = math.sqrt(mu / rho)
    dt = 0.1 * d / (cs * math.sqrt(3.0))
    steps_per_voxel = d / (cs * dt)
    return bx, mu, rho, d, dt, steps_per_voxel


def _run(n, n_steps, opts, every=20):
    bx, mu, rho, d, dt, _ = _setup(n=n)
    env = np.zeros(n_steps, np.float32)
    env[: max(1, n_steps // 3)] = 1.0
    ratios = []

    def cb(it, u):
        if it % every == every - 1:
            ratios.append((it, _div_curl_ratio(u, d)))

    shear_fdtd(
        bx, None, None, rho, mu, d, d, d, dt, n_steps, opts={**opts, "env_t": env}, callback=cb
    )
    return ratios


@pytest.mark.parametrize("damped", [False, True])
def test_homogeneous_point_force_stays_solenoidal(damped):
    """Until the wall signal reaches the inner half-cube the ratio is at the float32 floor."""
    n = 32
    _, _, _, _, _, steps_per_voxel = _setup(n=n)
    wall_to_region = n // 4  # voxels between the box wall and the measured region
    # Stop at half the nominal arrival time: with strong velocity damping the wall
    # signal spreads diffusively and leads the shear-speed front by ~20 %.
    n_steps = int(0.5 * wall_to_region * steps_per_voxel)
    opts = {"vel_damp": 0.02 if damped else 0.0, "eta": 0.5 if damped else 0.0}
    ratios = _run(n, n_steps, opts)
    assert ratios, "run too short to sample"
    assert max(r for _, r in ratios) < TOL, ratios


def test_wall_injects_divergence_without_reprojection():
    """Documents why ``reproject_every`` exists: after arrival the wall signal dominates."""
    n = 32
    _, _, _, _, _, steps_per_voxel = _setup(n=n)
    n_steps = int(1.5 * (n // 4) * steps_per_voxel)
    ratios = _run(n, n_steps, {"vel_damp": 0.02, "eta": 0.5})
    assert max(r for _, r in ratios) > 1e-2, ratios


def test_reproject_every_bounds_divergence_after_reflections():
    """With ``reproject_every`` the ratio stays below TOL for the whole run."""
    n = 32
    _, _, _, _, _, steps_per_voxel = _setup(n=n)
    n_steps = int(3.0 * (n // 4) * steps_per_voxel)
    ratios = _run(n, n_steps, {"vel_damp": 0.02, "eta": 0.5, "reproject_every": 20})
    assert max(r for _, r in ratios) < TOL, ratios


def test_reproject_every_rejects_negative():
    bx, mu, rho, d, dt, _ = _setup(n=8)
    env = np.ones(3, np.float32)
    with pytest.raises(ValueError, match="reproject_every"):
        shear_fdtd(
            bx, None, None, rho, mu, d, d, d, dt, 3, opts={"env_t": env, "reproject_every": -1}
        )
